### PR TITLE
Rails/ActiveSupport 6 allowed

### PR DESCRIPTION
**Pull request by szTheory**

### CODE REVIEW

**Comment by bklang** [comment]
Thanks for the contribution @szTheory. Have you done any testing with Rails 6? We locked it to `< 5.0.0` because that was the latest version we tested with. Can you comment on what testing you've done to ensure compatibility?

**Comment by szTheory** [comment]
Ran the specs locally with `bundle exec rake` and they all passed. I'm also running it in an app and CI specs around TTS are still passing.

**Comment by bklang** [comment]
CI looks ok - failure is due to bundler no longer support Ruby `< 2.3.0`. I'm going to merge this. Thanks for your contribution!

**Comment by sfgeorge** [comment]
@szTheory @bklang Head's up, this unfortunately got merged to master instead of the develop branch.  We may want to either remove from master, or merge master -> develop.

**Comment by bklang** [comment]
Thanks for catching that @sfgeorge ! I tried merging master back to develop, but it picks up a bunch of garbage commits that are artifacts of our release process.  I've cherry-picked the relevant commit back to develop, which I think will be the least obtrusive change.

**Pull request merged**
